name: CI

on:
  pull_request:
  push:
    branches: [master]
    tags: ['[0-9]+.[0-9]+.[0-9]+']

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  all:
    name: All
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install: Rust toolchain"
        uses: dsherret/rust-toolchain-file@v1

      - run: cargo b
